import Link from "next/link"
import { ArrowRight, Check, ChevronRight, Clock3, FileText, Gavel, Handshake, ShieldCheck, Sparkles } from "lucide-react"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { WhatsAppButton } from "@/components/whatsapp-button"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { AnimatedSection } from "@/components/animated-section"

const areas = [
  { number: "01", title: "Direito Civil", text: "Contratos, indenizações e relações patrimoniais conduzidos com segurança.", href: "/areas/civil", icon: Gavel },
  { number: "02", title: "Direito Trabalhista", text: "Estratégia para relações de trabalho, negociações e defesa de direitos.", href: "/areas/trabalhista", icon: Handshake },
  { number: "03", title: "Direito Empresarial", text: "Decisões jurídicas que acompanham o ritmo e os desafios do seu negócio.", href: "/areas/empresarial", icon: ShieldCheck },
  { number: "04", title: "Direito Previdenciário", text: "Planejamento e orientação para proteger seu futuro e seus benefícios.", href: "/areas/previdenciario", icon: FileText },
]

const steps = ["Entendemos o seu contexto", "Desenhamos a estratégia", "Atuamos com clareza", "Acompanhamos cada etapa"]

export default function HomePage() {
  return <><Header /><main>
    <section className="relative overflow-hidden bg-primary text-primary-foreground"><div className="absolute right-0 top-0 h-full w-1/3 border-l border-primary-foreground/10 opacity-40" /><div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 md:px-6 md:py-28 lg:grid-cols-[1.1fr_.9fr] lg:items-end lg:gap-20"><AnimatedSection animation="fade-in-up"><div><p className="mb-7 flex items-center gap-3 text-xs font-medium uppercase tracking-[.22em] text-accent"><span className="h-px w-10 bg-accent" /> Advocacia estratégica</p><h1 className="max-w-4xl font-serif text-5xl leading-[1.08] tracking-tight md:text-7xl">Direito com <em className="text-accent">presença</em> para decisões importantes.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-primary-foreground/70">A Lord Perrout Advocacia combina conhecimento técnico, escuta atenta e estratégia para cuidar do que realmente importa.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" variant="secondary" className="group"><Link href="/contato">Agendar uma conversa <ArrowRight data-icon="inline-end" className="transition-transform group-hover:translate-x-1" /></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/25 bg-transparent text-primary-foreground hover:bg-primary-foreground/10"><Link href="/areas">Conheça nossa atuação</Link></Button></div></div></AnimatedSection><AnimatedSection animation="scale-in" delay={200}><div className="relative flex min-h-[300px] flex-col justify-between border border-primary-foreground/20 bg-primary-foreground/[.04] p-7 md:min-h-[360px] md:p-10"><Sparkles className="size-6 text-accent" /><div><p className="font-serif text-3xl leading-tight md:text-4xl">&quot;A melhor estratégia começa quando alguém realmente escuta.&quot;</p><div className="mt-8 flex items-center gap-3 text-xs uppercase tracking-[.16em] text-primary-foreground/50"><span className="h-px w-8 bg-accent" /> Lord Perrout Advocacia</div></div></div></AnimatedSection></div></section>
    <section className="border-b border-border bg-secondary"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-8 md:grid-cols-3 md:px-6"><div className="flex items-center gap-4"><ShieldCheck className="size-7 text-accent" /><div><p className="font-semibold">Atuação personalizada</p><p className="text-sm text-muted-foreground">Cada caso merece uma estratégia própria.</p></div></div><div className="flex items-center gap-4"><Clock3 className="size-7 text-accent" /><div><p className="font-semibold">Respostas objetivas</p><p className="text-sm text-muted-foreground">Clareza para você decidir melhor.</p></div></div><div className="flex items-center gap-4"><Check className="size-7 text-accent" /><div><p className="font-semibold">Compromisso constante</p><p className="text-sm text-muted-foreground">Você acompanha tudo de perto.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 md:px-6 md:py-28"><AnimatedSection animation="fade-in-up"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">Como podemos ajudar</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight md:text-5xl">Experiência para proteger o seu próximo passo.</h2></div><Link href="/areas" className="group flex items-center gap-2 text-sm font-semibold text-primary">Ver todas as áreas <ArrowRight className="transition-transform group-hover:translate-x-1" /></Link></div></AnimatedSection><div className="mt-12 grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2">{areas.map((area, index) => { const Icon = area.icon; return <AnimatedSection key={area.title} animation="fade-in-up" delay={index * 80}><Link href={area.href} className="group block bg-background p-7 transition-colors hover:bg-secondary md:p-9"><div className="flex items-start justify-between"><span className="font-mono text-xs text-accent">{area.number}</span><Icon className="size-6 text-muted-foreground transition-colors group-hover:text-accent" /></div><h3 className="mt-12 font-serif text-2xl">{area.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{area.text}</p><span className="mt-7 flex items-center gap-2 text-sm font-semibold text-primary">Explorar área <ChevronRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link></AnimatedSection> })}</div></section>
    <section className="bg-secondary"><div className="mx-auto grid max-w-7xl gap-14 px-4 py-20 md:px-6 md:py-28 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><AnimatedSection animation="fade-in-up"><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">Nosso jeito de atuar</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Técnica sem distância. Estratégia sem complicação.</h2><p className="mt-6 max-w-md leading-7 text-muted-foreground">Do primeiro contato ao desfecho, construímos uma relação de confiança baseada em comunicação direta e decisões bem fundamentadas.</p><Button asChild className="mt-8"><Link href="/sobre">Conheça o escritório <ArrowRight data-icon="inline-end" /></Link></Button></AnimatedSection><div className="flex flex-col">{steps.map((step, index) => <AnimatedSection key={step} animation="fade-in-up" delay={index * 100}><div className="group flex items-center gap-5 border-b border-border py-6"><span className="font-mono text-sm text-accent">0{index + 1}</span><span className="font-serif text-2xl text-foreground transition-colors group-hover:text-primary md:text-3xl">{step}</span><ArrowRight className="ml-auto size-5 text-muted-foreground transition-transform group-hover:translate-x-1" /></div></AnimatedSection>)}</div></div></section>
    <section className="bg-primary px-4 py-20 text-center text-primary-foreground md:px-6 md:py-24"><AnimatedSection animation="fade-in-up"><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">O próximo passo é seu</p><h2 className="mx-auto mt-5 max-w-2xl font-serif text-4xl leading-tight md:text-5xl">Vamos conversar sobre o que importa para você?</h2><p className="mx-auto mt-5 max-w-xl text-primary-foreground/70">Agende uma conversa inicial e descubra como podemos construir uma solução jurídica segura.</p><Button asChild size="lg" variant="secondary" className="mt-9"><Link href="/contato">Falar com a nossa equipe <ArrowRight data-icon="inline-end" /></Link></Button></AnimatedSection></section>
  </main><Footer /><WhatsAppButton /></>
}
