"use client"

import Image from "next/image"
import Link from "next/link"
import { useState } from "react"
import { ArrowRight, Check, ChevronRight, Clock3, FileText, Gavel, Handshake, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { AnimatedSection } from "@/components/animated-section"

const areas = [
  { title: "Direito Civil", eyebrow: "Patrimônio e relações", text: "Contratos, indenizações e relações patrimoniais conduzidos com segurança e visão prática.", href: "/areas/civil", icon: Gavel },
  { title: "Direito Trabalhista", eyebrow: "Pessoas e empresas", text: "Estratégia para relações de trabalho, negociações e defesa de direitos em cada etapa.", href: "/areas/trabalhista", icon: Handshake },
  { title: "Direito Empresarial", eyebrow: "Negócios em movimento", text: "Decisões jurídicas que acompanham o ritmo e os desafios do seu negócio.", href: "/areas/empresarial", icon: ShieldCheck },
  { title: "Direito Previdenciário", eyebrow: "Proteção e futuro", text: "Planejamento e orientação para proteger seu futuro e seus benefícios.", href: "/areas/previdenciario", icon: FileText },
]

const steps = ["Entendemos o seu contexto", "Desenhamos a estratégia", "Atuamos com clareza", "Acompanhamos cada etapa"]

export function HomeExperience() {
  const [activeArea, setActiveArea] = useState(0)
  const area = areas[activeArea]
  const Icon = area.icon

  return <>
    <section className="relative overflow-hidden bg-primary text-primary-foreground">
      <div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 md:px-6 md:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:gap-16">
        <AnimatedSection animation="fade-in-up"><div><p className="mb-6 flex items-center gap-3 text-xs font-medium uppercase tracking-[.22em] text-accent"><span className="h-px w-10 bg-accent" /> Advocacia estratégica</p><h1 className="max-w-3xl font-serif text-5xl leading-[1.04] tracking-tight md:text-7xl">Direito com <em className="text-accent">presença</em> para decisões importantes.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-primary-foreground/70">A Lord Perrout Advocacia combina conhecimento técnico, escuta atenta e estratégia para cuidar do que realmente importa.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" variant="secondary" className="group"><Link href="/contato">Agendar uma conversa <ArrowRight data-icon="inline-end" className="transition-transform group-hover:translate-x-1" /></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/25 bg-transparent text-primary-foreground hover:bg-primary-foreground/10"><Link href="/areas">Conheça nossa atuação</Link></Button></div></div></AnimatedSection>
        <AnimatedSection animation="scale-in" delay={150}><div className="relative min-h-[370px] overflow-hidden border border-primary-foreground/20 bg-primary-foreground/[.04] md:min-h-[480px]"><img src="/images/lord-perrout-team.png" alt="Advogados da Lord Perrout em reunião no escritório" className="absolute inset-0 z-0 size-full object-cover opacity-90" fetchPriority="high" /><div className="absolute inset-0 z-10 bg-gradient-to-t from-primary via-primary/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 z-20 p-6 md:p-8"><p className="max-w-sm font-serif text-2xl leading-tight md:text-3xl">Técnica, proximidade e coragem para agir.</p><div className="mt-5 flex items-center gap-3 text-xs uppercase tracking-[.16em] text-primary-foreground/60"><span className="h-px w-8 bg-accent" /> Lord Perrout Advocacia</div></div></div></AnimatedSection>
      </div>
    </section>

    <section className="border-b border-border bg-secondary"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-8 md:grid-cols-3 md:px-6"><div className="flex items-center gap-4"><ShieldCheck className="size-7 text-accent" /><div><p className="font-semibold">Atuação personalizada</p><p className="text-sm text-muted-foreground">Cada caso merece uma estratégia própria.</p></div></div><div className="flex items-center gap-4"><Clock3 className="size-7 text-accent" /><div><p className="font-semibold">Respostas objetivas</p><p className="text-sm text-muted-foreground">Clareza para você decidir melhor.</p></div></div><div className="flex items-center gap-4"><Check className="size-7 text-accent" /><div><p className="font-semibold">Compromisso constante</p><p className="text-sm text-muted-foreground">Você acompanha tudo de perto.</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-20 md:px-6 md:py-28"><AnimatedSection animation="fade-in-up"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">Como podemos ajudar</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight md:text-5xl">A orientação certa muda o próximo passo.</h2></div><Link href="/areas" className="group flex items-center gap-2 text-sm font-semibold text-primary">Ver todas as áreas <ArrowRight className="transition-transform group-hover:translate-x-1" /></Link></div></AnimatedSection>
      <div className="mt-12 grid gap-8 lg:grid-cols-[.82fr_1.18fr]"><div className="flex flex-col border-y border-border">{areas.map((item, index) => { const ItemIcon = item.icon; return <button type="button" key={item.title} onClick={() => setActiveArea(index)} className={`group flex items-center gap-4 border-b border-border px-4 py-5 text-left transition-colors last:border-b-0 ${activeArea === index ? "bg-primary text-primary-foreground" : "hover:bg-secondary"}`}><span className={`font-mono text-xs ${activeArea === index ? "text-accent" : "text-muted-foreground"}`}>0{index + 1}</span><span className="flex-1"><span className="block text-xs uppercase tracking-[.15em] opacity-60">{item.eyebrow}</span><span className="mt-1 block font-serif text-2xl">{item.title}</span></span><ItemIcon className={`size-5 ${activeArea === index ? "text-accent" : "text-muted-foreground"}`} /></button> })}</div><div className="relative min-h-[350px] overflow-hidden bg-primary p-8 text-primary-foreground md:p-12"><div className="relative z-10 flex h-full flex-col justify-between"><div><Icon className="size-8 text-accent" /><p className="mt-10 text-xs uppercase tracking-[.2em] text-accent">{area.eyebrow}</p><h3 className="mt-3 font-serif text-4xl md:text-5xl">{area.title}</h3><p className="mt-5 max-w-md leading-7 text-primary-foreground/70">{area.text}</p></div><Link href={area.href} className="group mt-10 flex items-center gap-2 text-sm font-semibold">Explorar esta área <ChevronRight className="transition-transform group-hover:translate-x-1" /></Link></div><div className="absolute -bottom-16 -right-12 size-64 rounded-full border border-accent/20" /></div></div>
    </section>

    <section className="bg-secondary"><div className="mx-auto grid max-w-7xl gap-14 px-4 py-20 md:px-6 md:py-28 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><AnimatedSection animation="fade-in-up"><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">Uma relação de confiança</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Você não precisa enfrentar decisões difíceis sozinho.</h2><p className="mt-6 max-w-md leading-7 text-muted-foreground">Do primeiro contato ao desfecho, construímos uma relação baseada em comunicação direta e decisões bem fundamentadas.</p><Button asChild className="mt-8"><Link href="/sobre">Conheça o escritório <ArrowRight data-icon="inline-end" /></Link></Button></AnimatedSection><AnimatedSection animation="scale-in" delay={100}><div className="relative min-h-[380px] overflow-hidden"><img src="/images/lord-perrout-consultation.png" alt="Advogada conversando com cliente durante atendimento" className="absolute inset-0 size-full object-cover" fetchPriority="high" /><div className="absolute bottom-0 left-0 max-w-xs bg-primary p-5 text-primary-foreground"><p className="font-serif text-xl">Escuta que orienta. Estratégia que protege.</p></div></div></AnimatedSection></div></section>

    <section className="mx-auto max-w-7xl px-4 py-20 md:px-6 md:py-28"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">Nosso jeito de atuar</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Presença em cada etapa.</h2></div><div className="flex flex-col">{steps.map((step, index) => <div key={step} className="group flex items-center gap-5 border-b border-border py-6"><span className="font-mono text-sm text-accent">0{index + 1}</span><span className="font-serif text-2xl transition-colors group-hover:text-primary md:text-3xl">{step}</span><ArrowRight className="ml-auto size-5 text-muted-foreground transition-transform group-hover:translate-x-1" /></div>)}</div></div></section>

    <section className="bg-primary px-4 py-20 text-center text-primary-foreground md:px-6 md:py-24"><AnimatedSection animation="fade-in-up"><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">O próximo passo é seu</p><h2 className="mx-auto mt-5 max-w-2xl font-serif text-4xl leading-tight md:text-5xl">Vamos conversar sobre o que importa para você?</h2><p className="mx-auto mt-5 max-w-xl text-primary-foreground/70">Agende uma conversa inicial e descubra como podemos construir uma solução jurídica segura.</p><Button asChild size="lg" variant="secondary" className="mt-9"><Link href="/contato">Falar com a nossa equipe <ArrowRight data-icon="inline-end" /></Link></Button></AnimatedSection></section>
  </>
}
